CFLAGS = -g -Wall -Wextra -pedantic -Wno-unused-parameter
CC = gcc
HFILES = Algo1.h Algo2_1.h Algo2_2.h

Main : Main.o Algo1.o Algo2_1.o Algo2_2.o
	$(CC) -o $@ $(CFLAGS) $^ -lm

%.o : %.c 
	$(CC) $(GCC_FLAGS) -c $<
